In [9]:
import requests
import csv
from datetime import datetime
import numpy as np
import pandas as pd

In [6]:
def fetch_daily_adjusted(symbol):
    url = "https://alpha-vantage.p.rapidapi.com/query"
    querystring = {"function": "TIME_SERIES_DAILY_ADJUSTED", "symbol": symbol, "outputsize": "compact",
                   "datatype": "csv"}
    headers = {
        'x-rapidapi-key': "6e73a64168mshac6de5c58d04104p1f42f5jsnc6a5148414cc",
        'x-rapidapi-host': "alpha-vantage.p.rapidapi.com"
    }
    response = requests.request("GET", url, headers=headers, params=querystring)
    return response.content.decode('utf-8')


# def parse_csv(csv_content):
#     cr = csv.reader(csv_content.splitlines(), delimiter=',')
#     lines = list(cr)
#     csv_header = ['timestamp', 'open', 'high', 'low', 'close', 'adjusted_close', 'volume', 'dividend_amount',
#                   'split_coefficient']
#     for i in range(1, len(lines)):
#         row = lines[i]
#         str_timestamp = row[lines.index('timestamp')]
#         element = datetime.strptime(str_timestamp, "%Y-%m-%d")
#         timestamp = datetime.timestamp(element)

In [17]:
def fetch_daily_adj_csv(symbol):
    return 'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol={}&datatype=csv&apikey=6e73a64168mshac6de5c58d04104p1f42f5jsnc6a5148414cc'.format(symbol)

In [19]:
ewa = fetch_daily_adj_csv('EWA')
ewc = fetch_daily_adj_csv('EWC')

In [21]:
df_ewa = pd.read_csv(ewa)

In [22]:
df_ewa

,timestamp,open,high,low,close,adjusted_close,volume,dividend_amount,split_coefficient
0,2020-12-08,23.55,23.6900,23.540,23.67,23.67,1747931,0.0,1.0
1,2020-12-07,23.49,23.5900,23.435,23.51,23.51,2780442,0.0,1.0
2,2020-12-04,23.47,23.6100,23.470,23.57,23.57,3540449,0.0,1.0
3,2020-12-03,23.38,23.5000,23.330,23.37,23.37,10197053,0.0,1.0
4,2020-12-02,23.04,23.3000,23.000,23.26,23.26,8319709,0.0,1.0
...,...,...,...,...,...,...,...,...,...
95,2020-07-24,20.01,20.1000,19.945,20.03,20.03,2098345,0.0,1.0
96,2020-07-23,20.36,20.4200,20.100,20.16,20.16,1689933,0.0,1.0
97,2020-07-22,20.37,20.4699,20.320,20.43,20.43,1856337,0.0,1.0
98,2020-07-21,20.47,20.6000,20.430,20.48,20.48,2761212,0.0,1.0
99,2020-07-20,19.88,20.0200,19.810,20.00,20.00,1268578,0.0,1.0

In [23]:
df_ewc = pd.read_csv(ewc)
df_ewc

,timestamp,open,high,low,close,adjusted_close,volume,dividend_amount,split_coefficient
0,2020-12-08,31.24,31.475,31.24,31.43,31.43,1374479,0.0,1.0
1,2020-12-07,31.24,31.420,31.11,31.36,31.36,1945593,0.0,1.0
2,2020-12-04,30.96,31.340,30.96,31.34,31.34,1281280,0.0,1.0
3,2020-12-03,30.68,30.970,30.68,30.87,30.87,2007659,0.0,1.0
4,2020-12-02,30.41,30.660,30.32,30.66,30.66,2926720,0.0,1.0
...,...,...,...,...,...,...,...,...,...
95,2020-07-24,26.88,27.000,26.83,26.96,26.96,1293879,0.0,1.0
96,2020-07-23,27.25,27.350,26.95,27.03,27.03,1831840,0.0,1.0
97,2020-07-22,27.21,27.310,27.14,27.31,27.31,1348873,0.0,1.0
98,2020-07-21,27.37,27.470,27.16,27.18,27.18,2148336,0.0,1.0
99,2020-07-20,26.89,27.080,26.86,27.05,27.05,1325058,0.0,1.0

In [24]:
from johansen import coint_johansen

In [27]:
df = pd.DataFrame({'x':df_ewa['close'], 'y':df_ewc['close']})

In [28]:
coint_johansen(df, 0, 1)

--------------------------------------------------
--> Trace Statistics
variable statistic Crit-90% Crit-95%  Crit-99%
r = 0 	 13.3979 13.4294 15.4943 19.9349
r = 1 	 4.3061 2.7055 3.8415 6.6349
--------------------------------------------------
--> Eigen Statistics
variable statistic Crit-90% Crit-95%  Crit-99%
r = 0 	 9.0918 12.2971 14.2639 18.52
r = 1 	 4.3061 2.7055 3.8415 6.6349
--------------------------------------------------
eigenvectors:
 [[-0.01969694 -2.59740774]
 [-0.95388125  2.47113893]]
--------------------------------------------------
eigenvalues:
 [0.08860008 0.04298804]
--------------------------------------------------